apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  chart:
    spec:
      chart: authentik
      version: 2024.10.x
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  interval: 10m
  timeout: 5m
  releaseName: authentik
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values: |-
    authentik:
        secret_key: "PleaseGenerateASecureKey"
        # This sends anonymous usage-data, stack traces on errors and
        # performance data to sentry.io, and is fully opt-in
        error_reporting:
            enabled: true
        postgresql:
            password: "ThisIsNotASecurePassword"

    server:
        ingress:
            # Specify kubernetes ingress controller class name
            ingressClassName: traefik
            enabled: true
            hosts:
                - auth.local

    postgresql:
        enabled: true
        auth:
            password: "ThisIsNotASecurePassword"
    redis:
        enabled: true
