apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  chart:
    spec:
      chart: authentik
      version: 2024.12.x
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  interval: 10m
  timeout: 5m
  releaseName: authentik
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values: |-
    authentik:
      secret_key: "supersecret"
      log_level: trace
      postgresql:
        password: "supersecret"

    server:
      ingress:
        # Specify kubernetes ingress controller class name
        ingressClassName: traefik
        annotations: {}
        labels: {}
        enabled: true
        hosts:
          - auth.local
          paths:
            - path: "/"
              pathType: Prefix
        resources:
          requests:
            cpu: 2000m
            memory: 2Gi
          limits:
            memory: 3Gi
    postgresql:
      enabled: true
      persistence:
        size: 1Gi
      auth:
        password: "supersecret"
    redis:
      enabled: true
      master:
        persistence:
          size: 1Gi

    worker:
      resources:
          requests:
            cpu: 2000m
            memory: 2Gi
          limits:
            memory: 3Gi
