apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik-ingress
  namespace: authentik
spec:
  entryPoints:
    #- web
    - websecure
  routes:
    - match: Host(`auth.local`)
      kind: Rule
      middlewares:
      services:
        - name: authentik
          port: 80
