apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: podinfo-ingress
  namespace: podinfo
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`podinfo.local`)
      kind: Rule
      middlewares:
      - name: authentik
        namespace: authentik
      services:
        - name: podinfo
          port: 9898
